---
- name: 관리 대상 서버 초기 설정
  hosts: webservers 
  gather_facts: yes 

  vars_files:
    - vars/vault-passwords.yml
    - vars/main.yml 
  tasks: 
    #############################################
    # 1) SSH 공개 키 복사
    # 2) ansible유저 > wheel group --> NOPASSWD 
    # 3) nameserver 설정 
    # ) Python3 설치 확인 및 설치 
    # ) 
    #############################################
    # 1) SSH 공개 키 복사 
    - name: 1) 공개 키 복사 
      authorized_key:
        user: ansible
        state: present 
        key: "{{ lookup('file', ansible_home_dir + '/.ssh/id_rsa.pub') }}"
    
    # 2) ansible 유저 권한 상승
    - name: 2-1) ansible 유저를 wheel 그룹에 추가합니다.  
      user:
        name: ansible
        groups: wheel 
        append: yes 
    - name: 2-2) wheel 그룹 권한 상승 
      lineinfile: 
        path: /etc/sudoers 
        regexp: '^#\s+%wheel\s+ALL=\(ALL\)\s+NOPASSWD:\s+ALL$'
        line: '^%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
        state: present 
    
    # 3) nameserver 설정 
    - name: 3) nameserver 설정 
      copy: 
        content: |
          nameserver 8.8.8.8 
        dest: /etc/resolv.conf 
        owner: root 
        group: root 
        mode: '0644'
        backup: yes  
    
    # ) Python3 설치 확인 및 설치 
    - name: 1) Python3 설치 확인 및 설치 
      dnf:
        name: Python3
        state: present 