---
- name: 관리 대상 서버 초기 설정
  hosts: webservers 
  gather_facts: yes 

  vars_files:
    - vars/vault_passwords.yml
    - vars/main.yml 
  tasks: 
    #############################################
    # 1) SSH 공개 키 복사
    # 2) Python3 설치 확인 및 설치 
    # 2) 
    #############################################
    # 1) SSH 공개 키 복사 
    - name: 1) 공개 키 복사 
      authorized_key:
        user: ansible
        state: present 
        key: "{{ lookup('file', ansible_home_dir + '/.ssh/id_rsa.pub') }}"
    
    # 2) Python3 설치 확인 및 설치 
    - name: 1) Python3 설치 확인 및 설치 
      dnf:
        name: Python3
        state: present 