---
- name: 초기 설정 
  hosts: localhost
  connection : local 
  vars_files:
    - vars/main.yml 

  vars: 
    selected_ip_subnet: "{{ (ansible_prompt_result.user_input.split('.')[2]) | int }}"
    dynamic_hosts_entries:
      - ip: "192.168.{{ selected_ip_subnet }}.10"
        hostname: ansible 
      - ip: "192.168.{{ selected_ip_subnet }}.20"
        hostname: ansible1
      - ip: "192.168.{{ selected_ip_subnet }}.30"
        hostname: ansible2 
  pre_tasks: 
    - name: IP 대역 확인
      ansible.builtin.pause:
        prompt: "현재 사용중인 IP 주소를 입력 해주세요. (예: 192.168.20.10)"
        echo: yes
      register: ansible_prompt_result 


  tasks: 
    #########################################
    # 1) 초기 설정
    # 2) 설정파일 복사 
    # 3) 호스트 정보 추가
    # 4) ssh-key 생성
    #########################################

    #########################################
    # 1) 초기 설정 
    - name: 1-1) ansible 사용자를 wheel 그룹에 추가
      user: 
        name: ansible
        groups: wheel
        append: yes
    - name: 1-2) wheel 그룹에 NOPASSWD 권한 부여
      lineinfile:
        path: /etc/sudoers
        regexp: '^#\%wheel\s+ALL=\(ALL\)\s+NOPASSWD:\s+ALL$'
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        validate: "/usr/sbin/visudo -cf %s"
        state: present 
    
    #########################################
    # 2) 설정 파일 복사 
    - name: 2-1) 설정 파일 복사 - .bashrc, .vimrc  
      copy: 
        src: "{{ lookup('env', 'HOME') }}/gitcode/initial_setup/config_files/{{ item.name }}"
        dest: "{{ lookup('env', 'HOME') }}/{{ item.name }}" 
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: '0755'
      loop: "{{ config_files }}"      

    - name: 2-3) 설정 파일 적용 - .bashrc
      shell: source ~/.bashrc 
      args:
        executable: /bin/bash 
      changed_when: false  
      
    #########################################
    # 3) 호스트 정보 추가
    - name: 3) 호스트 정보 추가 
      lineinfile: 
        path: /etc/hosts
        regexp: "^{{ item.ip }}\\s+{{ item.hostname }}$"
        line: "{{ item.ip }} {{ item.hostname }}"
        state: present 
        create: yes
      loop: "{{ dynamic_hosts_entries }}" 

    #########################################
    # 4) SSH-KEY 생성 
    - name: 4) SSH-KEY 생성 
      openssh_keypair:
        path: "{{ ansible_home_dir }}/.ssh/id_rsa"
        type: rsa 
        size: 4096 
        passphrase: ''
        state: present 
      become: no 
