---
- name: 초기 설정 
  hosts: localhost
  connection : local 
  tasks: 
    #########################################
    # 1) 초기 설정
    # 2) 설정파일 복사 
    # 3) 
    #########################################

    #########################################
    # 1) 초기 설정 
    - name: 1-1) ansible 사용자를 wheel 그룹에 추가
      user: 
        name: ansible
        groups: wheel
        append: yes
    - name: 1-2) wheel 그룹에 NOPASSWD 권한 부여
      lineinfile:
        path: /etc/sudoers
        regexp: '^#\s*%wheel\s+ALL=\(ALL\)\s+NOPASSWD:\s+ALL$'
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        validate: "/usr/sbin/visudo -cf %s"
        state: present 
    
    #########################################
    # 2) 설정 파일 복사 
    - name: 2-1) 설정 파일 복사 - .bashrc  
      copy: 
        src: "{{ lookup('env', 'HOME') }}/gitcode/initial_setup/config_files/.bashrc"
        dest: "{{ lookup('env', 'HOME') }}/.bashrc" 
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: '0755'
      
    - name: 2-2) 설정 파일 복사 - .vimrc 
      copy:
        src: "{{ lookup('env', 'HOME') }}/gitcode/initial_setup/config_files/.vimrc"
        dest: "{{ lookup('env', 'HOME') }}/.vimrc" 
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: '0755'

    - name: 2-3) 설정 파일 적용 - .bashrc
      shell: source "{{ lookup('env', 'HOME') }}/.bashrc" 
      args:
        executable: /bin/bash 
      changed_when: false  
      